name: NovaStreamItems
version: 1.0.0
main: fr.gradegear.GradeGearPlugin
api-version: '1.21'
author: NovaStream
description: Équipements personnalisés par grades avec pack de ressources.
commands:
  customitems:
    description: Donne et administre les objets NovaStream Items.
    usage: /customitems <list|give|pack|reload>
    aliases: [nsi, novastreamitems]
    permission: novastreamitems.admin
permissions:
  novastreamitems.admin:
    description: Autorise l'utilisation des commandes NovaStream Items.
    default: op
