# Recettes reproduites d'après les deux captures.
ban-hammer:
  material: NETHERITE_AXE
  name: "§cBan Hammer"
  recipe:
    shape:
      - "CSC"
      - "GdG"
      - "CDC"
    ingredients:
      C: SCULK_CATALYST
      S: NETHERITE_SWORD
      G: GOLDEN_APPLE
      d: CHEST
      D: DISPENSER

unban-hammer:
  material: NETHERITE_AXE
  name: "§aUnban Hammer"
  recipe:
    shape:
      - "SCE"
      - "GDC"
      - "GPG"
    ingredients:
      S: NETHERITE_SWORD
      C: SCULK_CATALYST
      E: IRON_BLOCK
      G: GOLDEN_APPLE
      D: DISPENSER
      P: NETHERITE_PICKAXE

unban-contract:
  # Bloc temporaire que les autres joueurs doivent casser.
  block: RESPAWN_ANCHOR
