name: RandomTeleport
version: '1.0.0'
main: fr.ted30600.randomteleport.RandomTeleportPlugin
api-version: '1.21.10'
author: Ted30600
description: Menu Random Teleport style FrostMC pour Paper 1.21.10

commands:
  rtp:
    description: Ouvre le menu Random Teleport
    usage: /rtp
    aliases: [randomtp, randomteleport]

permissions:
  randomteleport.use:
    description: Permet d'utiliser le Random Teleport
    default: true
